### ISSUE TITLE
围观一下

### ISSUE THREAD

**Issue by zhangjingye03** [AisonSu/AutoGetZhixinElectiveCourse#1]
这里是高三狗一枚，并不熟悉python，不过大概看了下，给点建议

### 换行符问题

`oneclicknowhat.py`, [L72](../blob/master/oneclicknowhat.py#L72)
这里去除换行符要考虑平台的问题吧，windows是`\r\n`，Linux下是`\n`，MAC是`\r`

### 多次请求以及http header的精简问题

服务器在报名的时候已经拥挤不堪，不需要更多的请求和更大的包去让它受罪 :joy: 

`oneclicknowhat.py`, [L60-63](../blob/master/oneclicknowhat.py#L63)
1. 实际抓包显示python3在Post请求上去后会遵循网站返回的302访问`toIndex.di`，故只需要处理第60行的result即可
![wireshark](http://i1.piimg.com/4851/b46ccd7e08253f11.png)

---

`oneclicknowhat.py`, [L19-27](../blob/master/oneclicknowhat.py#L19)
2. 既然是抢课，需要让包更快地到达服务器，所以包头不能太臃肿（但是最好别开gzip，服务器端需要解压，说不准更慢；当然这需要对比试验与科学探究 :joy: ）
`Accept` `Accept-Encoding` `Accept-Language` `Origin` `Referer` `User-Agent` 实测并不需要，可考虑去除

---

由于对python不熟，以上纯属臆测和实验得出，敬请谅解。

期待你的nice work~ 加油！

---

P.S. 熬夜对身体不好

**Comment by AisonSu** [comment]
1.我的开发环境是在WIN下搭建的，目前也只考虑WIN（因为要赶这次的选修），但目前在WIN下测试（用记事本编辑）是没有换行符障碍的
2.貌似必须有一个读取存储cookie验证的过程，这里实测必须先访问login.di才能成功登录
3.包头确实没有用处，非常感谢；gzip我本身并没有使用，并不大清楚
4.吐槽一下这个系统的安全性好差，密码如果不修改很快就能被破解，同时就算修改了轮身份证号也能破解

**Comment by SmallOyster** [comment]
同是执信鸡，同样过来围观一下。

py白痴表示完全看不懂……

还好初中没有那么火爆……

系统安全性真的很值得担忧……
